version: '3.8'

services:
  wordpress:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../:/var/www/html
    ports:
      - "${WP_PORT:-8080}:80"
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
      WORDPRESS_DB_NAME: ${DB_NAME}
      WORDPRESS_DEBUG: ${WP_DEBUG:-1}
    depends_on:
      - db

  db:
    image: mysql:8.0
    volumes:
      - wordpress_db:/var/lib/mysql
    ports:
      - "${DB_PORT:-3306}:3306"
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}

volumes:
  wordpress_db: {}